version: '3'
services:
  bitcoind:
    image: dev/bitcoind
    container_name: dev_bitcoind
    command: bitcoind -datadir=/data
    hostname: bitcoind
    build: .
    ports:
     - "8332:8332"
    volumes:
     - .:/data