version: '3'
services:
  web:
    container_name: dev_btc_nginx
    image: nginx:latest
    ports:
      - "8339:8339"
    links:
      - bitcoind
    volumes:
      - ./btc.conf:/etc/nginx/conf.d/btc.conf
  bitcoind:
    build: .
    image: dev/btc
    container_name: dev_btc
    command: bitcoind -datadir=/data -addresstype=legacy
    hostname: bitcoind
    expose:
     - "8332"
    volumes:
     - .:/data