version: '3'
services:
  ethereum:
    build: .
    image: dev/ethereum
    container_name: dev_ethereum
#    command: geth --config /data/config.toml
    command: geth --dev --dev.period 10 --datadir "/data" --rpc --rpccorsdomain "*" --rpcapi "eth,net,web3,personal" --ws --wsapi "eth,net,web3,personal" console
    hostname: ethereum
    ports:
     - "8545:8545"
    volumes:
     - .:/data