version: '3'
services:
  ethereum:
    image: dev/ethereum
    container_name: dev_ethereum
    command: geth --config /data/config.toml
    hostname: ethereum
    build: .
    ports:
     - "8545:8545"
    volumes:
     - .:/data