version: '3'
services:
  ethereum:
    build: .
    image: dev/ethereum
    container_name: dev_ethereum
#    stdin_open: true
    tty: true
#    command: geth --config /data/config.toml
    command: geth --dev --dev.period 10 --datadir "/data/data" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcapi "eth,net,web3,personal" --ws --wsapi "eth,net,web3,personal" console
    hostname: ethereum
    expose:
     - "8545"
    ports:
     - "8545:8545"
    volumes:
     - .:/data