version: '3'
services:
  web:
    container_name: dev_ltc_nginx
    image: nginx:latest
    ports:
      - "9339:9339"
    links:
      - litecoind
    volumes:
      - ./ltc.conf:/etc/nginx/conf.d/ltc.conf
  litecoind:
    build: .
    image: dev/litecoind
    container_name: dev_litecoind
    command: litecoind -datadir=/data
    hostname: litecoind
    expose:
     - "9332"
    volumes:
     - .:/data