version: '3'
services:
  web:
    container_name: dev_usdt_nginx
    image: nginx:latest
    ports:
      - "8338:8338"
    links:
      - omnicored
    volumes:
      - ./usdt.conf:/etc/nginx/conf.d/usdt.conf
  omnicored:
    build: .
    image: dev/omnicored
    container_name: dev_usdt
    command: omnicored -datadir=/data
    hostname: omnicored
    expose:
     - "8332"
    volumes:
     - .:/data
