version: '3'
services:
  web:
    container_name: dev_bu_nginx
    image: nginx:latest
    ports:
      - "8348:8348"
      - "8349:8349"
    links:
      - btc
      - usdt
    volumes:
      - ./ng.conf:/etc/nginx/conf.d/ng.conf
  btc:
    build: ./btc
    image: dev/bu/btc
    container_name: dev_bu_btc
    command: bitcoind -datadir=/data -addnode=usdt:8333 -printtoconsole
    expose:
     - "8332"
     - "8333"
    volumes:
     - ./btc:/data
  usdt:
    build: ./usdt
    image: dev/bu/usdt
    container_name: dev_bu_usdt
    command: omnicored -datadir=/data -addnode=btc:8333 -printtoconsole
    expose:
     - "8332"
     - "8333"
    volumes:
     - ./usdt:/data